WORKING_DIR=`pwd`
LOCAL_BASH_PROFILE_FILE="bash_profile"
BASH_PROFILE_EXTENSION="sh"
LOCAL_BASH_PROFILE_PATH="$WORKING_DIR/$LOCAL_BASH_PROFILE_FILE.$BASH_PROFILE_EXTENSION"
HOMEUSER_BASH_PROFILE_PATH="$HOME/.$LOCAL_BASH_PROFILE_FILE"

echo $LOCAL_BASH_PROFILE_PATH
echo $HOMEUSER_BASH_PROFILE_PATH

ln -s $LOCAL_BASH_PROFILE_PATH $HOMEUSER_BASH_PROFILE_PATH
